runtime: go
api_version: go1

handlers:
- url: /public
  static_dir: ../public

- url: /.*
  script: _go_app

- url: /update_beers
  script: _go_app
  login: admin

- url: /_ah/remote_api
  script: _go_app
  login: admin
